param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Join-Lines {
    param([string[]]$Lines)
    return ($Lines -join [Environment]::NewLine)
}

function Get-RelativePathSafe {
    param(
        [string]$Root,
        [string]$Path
    )
    try {
        return [System.IO.Path]::GetRelativePath($Root, $Path)
    } catch {
        return $Path
    }
}

$resolvedRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
$projectName = Split-Path -Path $resolvedRoot -Leaf
$loopRoot = Join-Path $resolvedRoot ".ai\loops"
$reportsRoot = Join-Path $loopRoot "reports"

New-Item -ItemType Directory -Force -Path $loopRoot, $reportsRoot | Out-Null

$localRules = @()
foreach ($name in @("AGENTS.md", "CLAUDE.md", ".cursorrules", "README.md")) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $localRules += $name
    }
}

$buildFiles = @()
foreach ($name in @("Cargo.toml", "package.json", "pyproject.toml", "go.mod", "pom.xml", "build.gradle", "Makefile")) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $buildFiles += $name
    }
}

$sourceDirs = @()
foreach ($name in @("src", "crates", "frontend", "app", "lib", "packages")) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $sourceDirs += $name
    }
}

$docsDirs = @()
foreach ($name in @("docs", ".ai")) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $docsDirs += $name
    }
}

$taskSources = @()
foreach ($name in @("docs\tasks", ".ai\tasks", "docs\plans", ".github\issues")) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $taskSources += $name
    }
}

$checkCommands = @()
$checkScript = Join-Path $resolvedRoot "scripts\check.ps1"
if (Test-Path -LiteralPath $checkScript) {
    $checkCommands += "powershell -ExecutionPolicy Bypass -File scripts\check.ps1"
}

$focusedChecks = @()
$scriptsDir = Join-Path $resolvedRoot "scripts"
if (Test-Path -LiteralPath $scriptsDir) {
    $focusedChecks = Get-ChildItem -Path $scriptsDir -Filter "check-*.ps1" -File -ErrorAction SilentlyContinue |
        Sort-Object Name |
        Select-Object -ExpandProperty Name
}

if ((Test-Path -LiteralPath (Join-Path $resolvedRoot "Cargo.toml")) -and -not $checkCommands.Contains("cargo test --workspace")) {
    $checkCommands += "cargo test --workspace"
}
if (Test-Path -LiteralPath (Join-Path $resolvedRoot "package.json")) {
    $checkCommands += "npm test"
}

if ($localRules.Count -eq 0) { $localRules = @("(none detected; inspect README/docs before coding)") }
if ($buildFiles.Count -eq 0) { $buildFiles = @("(none detected)") }
if ($sourceDirs.Count -eq 0) { $sourceDirs = @("(none detected)") }
if ($docsDirs.Count -eq 0) { $docsDirs = @("(none detected)") }
if ($taskSources.Count -eq 0) { $taskSources = @("(none detected; derive from explicit user goal)") }
if ($checkCommands.Count -eq 0) { $checkCommands = @("(none detected; build a verification gate before coding loop)") }
if ($focusedChecks.Count -eq 0) { $focusedChecks = @("(none detected)") }

$profilePath = Join-Path $loopRoot "LOOP_PROFILE.md"
$statePath = Join-Path $loopRoot "state.json"

if ((Test-Path -LiteralPath $profilePath) -and -not $Force) {
    Write-Host "LOOP_PROFILE.md already exists. Use -Force to overwrite."
} else {
    $profile = @(
        "# Loop Profile: $projectName",
        "",
        "Generated by loop-engineering bootstrap. Review before running long tasks.",
        "",
        "## Project Root",
        "",
        $resolvedRoot,
        "",
        "## Project Purpose",
        "",
        "BLOCKED: replace this before any implementation loop. State why this software exists and what outcome it serves - not what it does, but why anyone builds it. This is the anchor every loop checks against. Example: ""Auto-trade on Polymarket to capture edge with <=50ms reaction; every millisecond of local processing is money.""",
        "",
        "## Loop Fit",
        "",
        "- repeat condition: BLOCKED until named. A loop needs a weekly-or-more recurring task, scheduled check, event trigger, or explicit owner reason to repeat.",
        "- why this should be a loop, not a one-shot prompt: BLOCKED until named.",
        "- skip loop when: the task is one-off, exploratory, judgment-heavy, or lacks an objective gate.",
        "",
        "## Trigger / Cadence",
        "",
        "- default trigger: manual",
        "- scheduled loops: none until explicitly configured.",
        "- event-triggered loops: none until explicitly configured.",
        "",
        "## Local Rules",
        "",
        ($localRules | ForEach-Object { "- $_" }),
        "",
        "## Project Shape",
        "",
        "- build/package files: $($buildFiles -join ', ')",
        "- source dirs: $($sourceDirs -join ', ')",
        "- docs/state dirs: $($docsDirs -join ', ')",
        "",
        "## Task Source",
        "",
        ($taskSources | ForEach-Object { "- $_" }),
        "",
        "## Completion Authority",
        "",
        "Global gates:",
        "",
        ($checkCommands | ForEach-Object { "- $_" }),
        "",
        "Focused gates:",
        "",
        ($focusedChecks | Select-Object -First 30 | ForEach-Object {
            if ($_ -like "(*") {
                "- $_"
            } else {
                "- scripts\$_"
            }
        }),
        "",
        "## Budget Guard",
        "",
        "- max iterations: 1 implementation attempt, then repair only if the same gate fails for an understood reason.",
        "- max files changed: 8 tracked files per loop step.",
        "- max verification: one focused gate first, then the global gate if required by local rules.",
        "- max live actions: only when required by acceptance.",
        "- max permissions: read-only until a write-capable connector action is named; human approval before merge, deploy, dependency, credential, or production-data changes.",
        "",
        "## Permission Boundary",
        "",
        "- read-only connectors: allowed when needed for evidence.",
        "- write-capable connectors: BLOCKED until named with scope.",
        "- human approval required before: merge, deploy, dependency updates, credential changes, production-data writes, or external notifications.",
        "- secret/logging rule: do not write secrets, tokens, cookies, or credential material into reports or logs.",
        "",
        "## Active Loops",
        "",
        "### capability-task",
        "",
        "- task source: use the first concrete task source above, or the explicit user goal if no ledger exists.",
        "- trigger: manual by default; change only when a scheduled or event trigger is named.",
        "- allowed scope: the current task only.",
        "- gate: the narrowest focused gate, then the global gate if required by local rules.",
        "- report: .ai/loops/reports/<timestamp>-capability-task.md.",
        "- stop: unclear goal, no gate, more than 8 files, repeated unrelated failures, or fake success pressure.",
        "",
        "### regression",
        "",
        "- trigger: before merge, release, or broad-risk change.",
        "- gate: the global gate listed above.",
        "- report: .ai/loops/reports/<timestamp>-regression.md.",
        "- stop: do not edit code unless the user asked for repair.",
        "",
        "## State",
        "",
        "- state file: .ai/loops/state.json",
        "- report dir: .ai/loops/reports",
        "",
        "## Non-Negotiables",
        "",
        "- no fake success",
        "- no hidden fallback",
        "- no broad refactor inside one loop step",
        "- no completion claim without the named authority passing",
        "- every task ledger entry must state the larger goal it serves, not just what it produces. A task that only declares `done` without explaining what bigger outcome it feeds is incomplete. Each entry must carry three layers: `done` (what the task itself produces), `serves` (the larger chain goal this output is for - name the downstream milestone, product step, or architecture target that depends on it), and `chain-gate` (how a reader proves this task's output is actually reachable by the next link, not just internally correct - 'function compiles' or 'handshake succeeds' is a module gate, not a chain gate). This exists because tasks repeatedly satisfied their local `done` while the larger goal stayed unreachable: a component works in isolation but its output is never consumed by the downstream link it was created for. A task is complete when its output is proven to advance the chain, not when its own function works."
    )
    Set-Content -LiteralPath $profilePath -Value (Join-Lines -Lines $profile) -Encoding UTF8
    Write-Host "Wrote $profilePath"
}

if ((Test-Path -LiteralPath $statePath) -and -not $Force) {
    Write-Host "state.json already exists. Use -Force to overwrite."
} else {
    $state = [ordered]@{
        schema_version = "loop-engineering.state.v1"
        project = $projectName
        project_root = $resolvedRoot
        active_loop = $null
        current_task = $null
        iteration = 0
        last_gate = $null
        last_result = $null
        failures = @()
        completed_loops_since_step_back = 0
        last_report = $null
        updated_at = (Get-Date).ToUniversalTime().ToString("o")
    }
    $state | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $statePath -Encoding UTF8
    Write-Host "Wrote $statePath"
}

foreach ($name in @("capability-task", "plan-integrity", "regression", "source-health", "frontend-contract", "release-closure")) {
    New-Item -ItemType Directory -Force -Path (Join-Path $loopRoot $name) | Out-Null
}

Write-Host "Loop engineering bootstrap complete for $resolvedRoot"
